version: "3.12"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopnex-backend
    container_name: shopnex-backend
    ports:
      - "8000:9000"  # Host port 8000 -> container port 9000
    env_file:
      - .env
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Web UI
    volumes:
      - ./minio-data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
