[tool.isort]
profile = "black"
line_length = 88
force_single_line = true

known_fastapi = ["fastapi"]
known_zevrin = ["config", "models", "services", "scripts", "app"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FASTAPI", "ZEVRIN", "LOCALFOLDER"]

import_heading_stdlib = "Standard Imports"
import_heading_thirdparty = "Third Party Imports"
import_heading_fastapi = "FastAPI Imports"
import_heading_zevrin = "Zevrin Imports"

