name: Zevrin Frontend App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Install Dependencies & Build
        working-directory: frontend
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.ZEVRIN_VERCEL_TOKEN }} --cwd=frontend --confirm --scope=${{ secrets.ZEVRIN_APP_ORG }} --project=${{ secrets.ZEVRIN_APP_PROJ }}